---
title: "Informacje ogólne"
---

## Analiza danych w czasie rzeczywistym

Kod: 222890-S

Semestr letni 2025/2026,
SGH Szkoła Główna Handlowa w Warszawie

Szczegółowy opis znajdziesz w [sylabusie](sylabus.qmd).
Znajdziesz w nim opis wszystkich wykładów i ćwiczeń oraz proponowaną literaturę.

Inne książki zamieszczone zostały w zakładce [książki](ksiazki.qmd).

## Kalendarz

### Wykład

Wykład jest realizowany w trybie stacjonarnym.
Jest on NIEOBOWIĄZKOWY i odbywa się w Auli I bud. G.

1. ~~28.02.2026 Wykład 1 — 8:00–9:40~~
2. 14.03.2026 Wykład 2 — 8:00–9:40

### Laboratoria

1. 28.03.2026 Lab1 — DS1-16 11:40–13:20, 13:30–15:10, 15:20–17:00, 17:10–18:50 (Dni Otwarte SGH)
2. 29.03.2026 Lab1 — G-116 9:50–11:30, 11:40–13:20, 13:30–15:10, 15:20–17:00
3. 18.04.2026 Lab2 — DS1-16 11:40–13:20, 13:30–15:10, 15:20–17:00, 17:10–18:50
4. 19.04.2026 Lab2 — G-116 9:50–11:30, 11:40–13:20, 13:30–15:10, 15:20–17:00
5. 09.05.2026 Lab3 — DS1-16 11:40–13:20, 13:30–15:10, 15:20–17:00, 17:10–18:50
6. 10.05.2026 Lab3 — G-116 9:50–11:30, 11:40–13:20, 13:30–15:10, 15:20–17:00
7. 30.05.2026 Lab4 — DS1-16 11:40–13:20, 13:30–15:10, 15:20–17:00, 17:10–18:50 (Zastępstwo)
8. 31.05.2026 Lab4 — G-116 9:50–11:30, 11:40–13:20, 13:30–15:10, 15:20–17:00 (Zastępstwo)
9. 13.06.2026 Lab5 — DS1-16 11:40–13:20, 13:30–15:10, 15:20–17:00, 17:10–18:50
10. 14.06.2026 Lab5 — G-116 9:50–11:30, 11:40–13:20, 13:30–15:10, 15:20–17:00

### Zaliczenie

Wykłady zakończą się testem (na pierwszych zajęciach laboratoryjnych) — 20 pytań.
Aby zaliczyć test, należy zdobyć więcej niż 13 punktów — jest to warunek konieczny do zaliczenia przedmiotu.

Podczas laboratoriów będą zadawane prace domowe, które należy przesyłać za pośrednictwem MS Teams.
Każdy brak pracy domowej obniża końcową ocenę o 0,5 stopnia.

#### Projekt

Projekty należy realizować w grupach maksymalnie 5-osobowych.

Wymagania projektu:

- Projekt powinien rozwiązywać realny problem biznesowy, który można opracować przy użyciu danych przetwarzanych w trybie online (nie wyklucza to użycia przetwarzania wsadowego, np. do generowania modelu).
- Dane powinny być przesyłane do Apache Kafka, skąd będą poddawane dalszemu przetwarzaniu i analizie.
- Można używać dowolnego języka programowania w każdym komponencie projektu.
- Można wykorzystać narzędzia BI.
- Źródłem danych może być dowolne API, sztucznie generowane dane, IoT itp.

## Technologie

Uczestnicząc w zajęciach, musisz opanować i przynajmniej w podstawowym zakresie posługiwać się następującymi technologiami:

1. [Git](info.qmd#git)
2. Python, Jupyter Notebook, Google Colab
3. [Docker i Docker Compose](info.qmd#docker)
4. **Apache Spark**, **Apache Kafka**
