---
title: "Informacje ogólne"
---

## Analiza danych w czasie rzeczywistym

Kod: 222890-D

Semestr: 2025/2026
Uczelnia: SGH Szkoła Główna Handlowa w Warszawie

Podstawowe informacje o kursie znajdziesz w [sylabusie](/sylabus).

Polecane materiały znajdziesz na liście [książek](/ksiazki). 

## Kalendarz

### Wykład 

Wykład jest realizowany w trybie stacjonarnym.
Jest on NIEOBOWIĄZKOWY i odbywa się w Auli VI bud G

1.  - Wykład 1
    
Wykład 5 kończy się TESTEM: 20 pytań - 30 minut. 
Test przeprowadzany jest za pośrednictwem MS Teams.

### Laboratoria

#### Lab1



### Zaliczenie i Egzamin

Laboratoria

Podczas laboratoriów będą zadawane prace domowe, które należy przesyłać za pośrednictwem MS Teams.
Każdy brak pracy domowej obniża końcową ocenę o 0,5 stopnia.

#### Projekt

Projekty należy realizować w grupach maksymalnie 5-osobowych.

Wymagania projektu:

- Projekt powinien rozwiązywać realny problem biznesowy, który można opracować przy użyciu danych przetwarzanych w trybie online. (Nie wyklucza to użycia przetwarzania wsadowego, np. do generowania modelu).
- Dane powinny być przesyłane do Apache Kafka, skąd będą poddawane dalszemu przetwarzaniu i analizie.
- Można używać dowolnego języka programowania w każdym komponencie projektu.
- Można wykorzystać narzędzia BI.
- Źródłem danych może być dowolne API, sztucznie generowane dane, IoT itp.

## Technologie

Uczestnicząc w zajęciach musisz opanować i przynajmniej w podstawowym zakresie posługiwać się następującymi technologiami informatycznymi:

1. [GIT](/info.html#git) 
2. Python, Jupyter notebook, Jupyter lab, Colab
3. [Docker](/info.html#docker)
4. **Apache Spark**, **Apache Kafka**.