---
title: Książki i materiały
---

## Literatura podstawowa

Pozycje bezpośrednio związane z tematyką kursu.

### Przetwarzanie strumieniowe

1. G. Shapira, T. Palino, R. Sivaram, K. Petty — _Kafka: The Definitive Guide. Real-time data and stream processing at scale_, O'Reilly 2022. [Dostęp online](https://www.confluent.io/resources/kafka-the-definitive-guide-v2/)
2. G. Maas, F. Garillot — _Stream Processing with Apache Spark_, O'Reilly 2019. [Zobacz opis](https://helion.pl/view/111546/e_11pp.html)
3. F. Hueske, V. Kalavri — _Stream Processing with Apache Flink_, O'Reilly 2019. [Zobacz opis](https://helion.pl/view/111546/e_13f8.html)
4. A. Bellemare — _Mikrousługi oparte na zdarzeniach. Wykorzystanie danych w organizacji na dużą skalę_, O'Reilly 2021. [Zobacz opis](https://helion.pl/view/111546/miopzd)
5. T. Akidau, S. Chernyak, R. Lax — _Streaming Systems: The What, Where, When, and How of Large-Scale Data Processing_, O'Reilly 2018.

### Apache Spark

1. J. S. Damji, B. Wenig, T. Das, D. Lee — _Spark. Błyskawiczna analiza danych_, Helion. [Zobacz opis](https://helion.pl/view/111546/sparb2.html)
2. B. Chambers, M. Zaharia — _Spark: The Definitive Guide. Big Data Processing Made Simple_, O'Reilly. [Zobacz opis](https://helion.pl/view/111546/e_0qdv.html)
3. _Spark. Zaawansowana analiza danych_, Helion. [Zobacz opis](https://helion.pl/view/111546/sparkz.html)
4. J. Quddus — _Machine Learning with Apache Spark Quick Start Guide_, Packt. [Zobacz opis](https://helion.pl/view/111546/e_15el.html)

### MLOps i deployment modeli

1. N. Gift, A. Deza — _Practical MLOps: Operationalizing Machine Learning Models_, O'Reilly 2022.
2. V. Lakshmanan, S. Robinson, M. Munn — _Wzorce projektowe uczenia maszynowego_, O'Reilly 2021.

## Literatura uzupełniająca

### Uczenie maszynowe w Pythonie

1. A. Géron — _Uczenie maszynowe z użyciem Scikit-Learn i TensorFlow. Wydanie II_, Helion. [Zobacz opis](https://helion.pl/view/111546/uczem2.html)
2. W. McKinney — _Python w analizie danych. Wydanie II_, Helion. [Zobacz opis](https://helion.pl/view/111546/pytand.html)
3. J. Grus — _Data science od podstaw. Analiza danych w Pythonie. Wydanie II_, Helion. [Zobacz opis](https://helion.pl/view/111546/dascp2.html)
4. S. Raschka — _Python. Uczenie maszynowe. Wydanie II_, Helion. [Zobacz opis](https://helion.pl/view/111546/pythu2.html)
5. T. Hastie, R. Tibshirani, J. Friedman — _The Elements of Statistical Learning_, Springer 2017. [Dostęp online](https://hastie.su.domains/ElemStatLearn/)

### Deep Learning

1. F. Chollet — _Deep Learning. Praca z językiem Python i biblioteką Keras_, Helion. [Zobacz opis](https://helion.pl/view/111546/delepy.html)
2. J. Howard, S. Gugger — _Deep learning dla programistów. Budowanie aplikacji AI za pomocą fastai i PyTorch_, Helion. [Zobacz opis](https://helion.pl/view/111546/delepr.html)
3. A. Koul, S. Ganju, M. Kasam — _Practical Deep Learning for Cloud, Mobile & Edge_, O'Reilly 2019.

### Docker i narzędzia

1. J. Krochmalski — _Docker. Projektowanie i wdrażanie aplikacji_, Helion. [Zobacz opis](https://helion.pl/view/111546/docpro.html)
2. P. Bell, B. Beer — _GitHub. Przyjazny przewodnik_, Helion. [Zobacz opis](https://helion.pl/view/111546/github.html)

### Programowanie w Pythonie

1. C. Althoff — _Programista Samouk_, Helion. [Zobacz opis](https://helion.pl/view/111546/proprs)
2. A. Sweigart — _Automatyzacja nudnych zadań z Pythonem_, Helion. [Zobacz opis](https://helion.pl/view/111546/autopy)

### Quantum Computing

1. A. Jacquier, O. Kondratyev — _Quantum Machine Learning and Optimisation in Finance. On the Road to Quantum Advantage_.

## Przydatne strony WWW

### Oprogramowanie

1. [GitHub](https://github.com/)
2. [Git — dokumentacja (po polsku)](https://git-scm.com/book/pl/v2)
3. [Python](https://www.python.org/downloads/)
4. [PyPI — repozytorium bibliotek](https://pypi.python.org/pypi)
5. [Docker](https://docs.docker.com/get-docker/)
6. [Apache Kafka](https://kafka.apache.org/)
7. [Apache Spark](https://spark.apache.org/)

### Biblioteki Pythonowe

1. [NumPy](https://numpy.org)
2. [Pandas](https://pandas.pydata.org)
3. [Scikit-learn](https://scikit-learn.org/stable)
4. [Matplotlib](https://matplotlib.org)
5. [JupyterLab](https://jupyter.org)
6. [TensorFlow](https://www.tensorflow.org)
7. [Keras](https://keras.io)
8. [Beautiful Soup](https://www.crummy.com/software/BeautifulSoup)

### Edytor

1. [Visual Studio Code](https://code.visualstudio.com)

### Zbiory danych

- [Kaggle Datasets](https://www.kaggle.com/datasets)
- [Google Dataset Search](https://datasetsearch.research.google.com/)
- [UCI Machine Learning Repository](https://archive.ics.uci.edu/)
- [Reddit r/datasets](https://reddit.com/r/datasets)
- [Public APIs](https://github.com/toddmotto/public-apis)
- [KDnuggets](https://www.kdnuggets.com)

### Kursy i materiały

1. [Kurs ML — Andrew Ng (YouTube)](https://www.youtube.com/watch?v=PPLop4L2eGk&list=PLLssT5z_DsK-h9vYZkQkYNWcItqhlRJLN)
2. [Python Programming for Data Science — T. Beuzen](https://www.tomasbeuzen.com/python-programming-for-data-science/README.html)
3. [Chris Albon — Data Science & AI Notes](https://chrisalbon.com/)
